# Proyecto 2 - Metodos Numericos

In [23]:
import pandas as pd
import numpy as np
from scipy.linalg import solve
from sklearn.linear_model import LinearRegression
from numpy.polynomial.polynomial import Polynomial
from scipy.interpolate import lagrange

## - Problema 1

### Data

In [5]:
ds = pd.read_csv("ventas.csv")
ds = ds.set_index('Semana')

In [6]:
ds

q1   p1  q2  p2  q3   p3
Semana                          
1        4  108  59  73  37  102
2       11   91  38  86  36  103
3        4  114  62  70  80   77
4        7  100  50  75  66   83
5       10   96  61  72  45   94
6        6  100  65  70  40   98
7       11   94  26  93  19  121
8        7  100  20  95  16  124
9        5  111  54  74  44   96
10       8  101  29  89  41   98
11       4  117  23  93  17  130
12       9   98  32  88  44   97

### Variables

In [7]:
# Variables dependientes
y1 = ds['q1']
y2 = ds['q2']
y3 = ds['q3']

# Variables independientes
x = ds[['p1', 'p2', 'p3']]

### Creación de modelos

In [8]:
lr1 = LinearRegression(fit_intercept=True)
lr2 = LinearRegression(fit_intercept=True)
lr3 = LinearRegression(fit_intercept=True)

In [9]:
# Modelos
model1 = lr1.fit(x, y1)
model2 = lr2.fit(x, y2)
model3 = lr3.fit(x, y3)

### Componentes

In [10]:
# Componentes modelo 1
m1_b0 = model1.intercept_
m1_b1 = model1.coef_[0]
m1_b3 = model1.coef_[1]
m1_b2 = model1.coef_[2]

# Componentes modelo 2
m2_b0 = model2.intercept_
m2_b1 = model2.coef_[0]
m2_b3 = model2.coef_[1]
m2_b2 = model2.coef_[2]

# Componentes modelo 3
m3_b0 = model3.intercept_
m3_b1 = model3.coef_[0]
m3_b3 = model3.coef_[1]
m3_b2 = model3.coef_[2]

### Modelos finales

In [11]:
sign = lambda x: " +" if x > 0 else " "

In [12]:
print("y = " + str(m1_b0) + sign(m1_b1)+ str(m1_b1) + "*p1" + sign(m1_b2) + str(m1_b2) + "*p2" + sign(m1_b3) + str(m1_b3) + "*p3")
print("y = " + str(m2_b0) + sign(m2_b1)+ str(m2_b1) + "*p1" + sign(m2_b2) + str(m2_b2) + "*p2" + sign(m2_b3) + str(m2_b3) + "*p3")
print("y = " + str(m3_b0) + sign(m3_b1)+ str(m3_b1) + "*p1" + sign(m3_b2) + str(m3_b2) + "*p2" + sign(m3_b3) + str(m3_b3) + "*p3")

y = 31.7294164038644 -0.27899230242207235*p1 -0.022599296900742166*p2 +0.07775713214967682*p3
y = 197.85849520253134 -0.146322288224096*p1 +0.12402616949090281*p2 -1.868107907159624*p3
y = 97.97580071689424 +0.4688242075331577*p1 -1.2897110647735786*p2 +0.31692561180937817*p3


## - Problema 2

In [13]:
# Matriz de componentes con margen de 0.7 para conseguir
a = np.array([[0.7*m1_b1*2, m1_b2, m1_b3, -1*m1_b0], 
              [m2_b1, 0.7*m2_b2*2, m2_b3, -1*m2_b0], 
              [m3_b1, m3_b2, 0.7*m3_b3*2, -1*m3_b0]])


# Array para resultados
x = np.zeros(3)
n = 3

### Solución de sistema por Gauss Jordan

In [14]:
# Gauss Jordan Elimination
for i in range(n):
    if a[i][i] == 0.0:
        print('Division by zero')
        exit()
        
    for j in range(n):
        if i != j:
            ratio = a[j][i]/a[i][i]
            

            for k in range(n+1):
                a[j][k] = a[j][k] - ratio * a[i][k]

# Calculate solutio
for i in range(n):
    x[i] = a[i][n]/a[i][i]

# Print solution
print('\nSolution')
for i in range(n):
    print('p%d = %0.2f' %(i+1,x[i]), end = '\t')


Solution
p1 = 94.97	p2 = 149.14	p3 = 112.34	

## - Problema 3

In [19]:
# Variables dependientes separadas
lag_y1 = ds['q1'].to_numpy()
lag_y2 = ds['q2'].to_numpy()
lag_y3 = ds['q3'].to_numpy()

# Variables independientes separadas
lag_x1 = ds['p1'].to_numpy()
lag_x2 = ds['p2'].to_numpy()
lag_x3 = ds['p3'].to_numpy()

In [27]:
lag_y1

array([ 4, 11,  4,  7, 10,  6, 11,  7,  5,  8,  4,  9], dtype=int64)

In [28]:
lag_x1

array([108,  91, 114, 100,  96, 100,  94, 100, 111, 101, 117,  98],
      dtype=int64)

In [33]:
poly = lagrange(lag_x1, lag_y1)

In [69]:
x = np.array([4,6,7,10,11])

y = np.array([108,100,100,96,94])

poly = lagrange(x, y)

In [70]:
Polynomial(poly).coef

array([ 4.44444444e-02, -1.47777778e+00,  1.77888889e+01, -9.26888889e+01,
        2.77333333e+02])

In [57]:
poly

poly1d([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])